### ISSUE TITLE
v0.6 compatibility - question

### ISSUE THREAD

**Issue by maxruby** [JuliaGL/GLVisualize.jl#159]
@SimonDanisch.  I have tried to install `GLVisualize.jl` on my MacOS Sierra 10.12.3 with julia `v0.6-pre-alpha` (built 22 days ago) but got several precompilation errors.  I will share the errors later (as I do not have access to the laptop now). In the meantime, just wanted to know, is`GLVisualize.jl` already known to work fine on OSX  with latest julia `v0.6`? Are there known installation issues and/or are you currently working on `v0.6` compatibility?

**Comment by SimonDanisch** [comment]
Sorry, but 0.6 is not supported right now... I really need to stark working on that, now that StaticArrays works  with 0.6!

**Comment by maxruby** [comment]
Thanks for the quick reply.  Do you know how much/long it might take to have it v0.6-compatible?

**Comment by SimonDanisch** [comment]
Good question! Biggest blocking point is the switch to StaticArrays! I will take a look at it today...

**Comment by pablosanjose** [comment]
I would love to be able to move to GLVisualize on v0.6. Although the GLVisualize time-to-first-plot is still a bit long, the performance is otherwise great. Any news here? Difficult roadblocks? Thanks for the work!

**Comment by SimonDanisch** [comment]
I started working on it this weekend! It started great, but then I run into a few weird bugs.
Let me finish up the release of GPUArrays and then I'm 100% back on this!

**Comment by timholy** [comment]
Given its heavy use of Reactive, I wouldn't be surprised if https://github.com/JuliaGizmos/Interact.jl/issues/161 (see also https://github.com/JuliaLang/julia/issues/21141) is a major problem. I'm sticking with 0.5 until that's fixed.

**Comment by SimonDanisch** [comment]
![image](https://cloud.githubusercontent.com/assets/1010467/24861929/cbd5ef36-1dfa-11e7-8db6-552a8236d625.png)

**Comment by SimonDanisch** [comment]
If you want to try!
```Julia
for pkg in ("GLAbstraction", "GeometryTypes", "GLWindow")
    Pkg.checkout(pkg, "sd/staticarrays")
end
Pkg.checkout("ModernGL", "sd/v06")
Pkg.checkout("StaticArrays", "sd/fixedsizearrays")
Pkg.clone("https://github.com/JuliaGraphics/FreeTypeAbstraction.jl.git")
Pkg.checkout("FreeTypeAbstraction", "sd/v06")
```
Still a lot of deprecation warnings and it segfaults at `examples/lines/contourlines.jl` ... Julia 0.6 really likes segfaulting -.-

**Comment by SimonDanisch** [comment]
This is solved in the newest release:
https://github.com/JuliaLang/METADATA.jl/pull/10247
